### ISSUE TITLE
RPC config update

### ISSUE THREAD

**Issue by kehiy** [zurvan-lab/redvin#28]
Our current rpc config is:

```toml
[rpc]
enable_rpc = true
```

We need to update it to:

```toml
[rpc]
enable_grpc = true
grpc_port =  9090
```

**In config.toml, lib.rs and config.md**
